### PR TITLE
Alt event view #22

### PR DESCRIPTION
**Pull request by aenegri**
Now, view your events daily, weekly, or monthly. Changes include:
- Tracking and displaying the date of each
- Adding new compareTo and equals functions to necessary classes
- Additional functionality for CalendarDate
- Unit testing for the two main new methods

Before approving, please checkout and test it with several events, including some repeatable ones. Unit testing is somewhat limited because of the software design.

### CODE REVIEW

**Comment by hzhan147** [comment]
good work and the program works well.

**Comment by jzalden** [comment]
While good, I have a suggestion.
I would like the events on the selected day to appear in bold on the events list for the events in that week/month. It would make it more clear which event is on which day.

A harder idea: selecting weekly view should only make you able to select that whole week and not individual days in that week(in the calendar on the left.) changing what looks like it is selected. 

I think at least one of these is necessary.

**Comment by aenegri** [comment]
I implemented the suggested change. Ignore Travic CI for now, it is not configured correctly yet.

**Comment by jzalden** [comment]
looks good. ready to merge. please change the title to include the task number

**Pull request merged**
