### PR TITLE
Google Drive Export [WIP]

### PR DESCRIPTION
**Pull request by jzalden**
Fix and Reupload of Andrew's PR here: [WIP GDrive Support User Story 44](https://github.com/ser316asu/SER316-Karlsruhe/pull/26)

### CODE REVIEW

**Comment by jzalden** [comment]
Client Secret needed to test this feature. [check here to get an API key](https://console.developers.google.com)
Not uploaded to prevent spam abuse of the API allowance

**Comment by aenegri** [comment]
Added my changes in now

**Comment by aenegri** [comment]
Everything is working now. Just make sure to have the client_id file set up

**Comment by jzalden** [comment]
Conflicts resolved. 
Merging

**Pull request merged**
